version: "3.9"
services:
  radiko-auto-downloader:
    build: .
    image: iomz/radiko-auto-downloader:latest
    container_name: radiko-auto-downloader
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml
      - ./downloads:/downloads
