version: "3.9"
services:
  radicron:
    build: .
    image: iomz/radicron:latest
    container_name: radicron
    restart: unless-stopped
    user: "$UID:$GID"
    volumes:
      - ./config.yml:/app/config.yml
      - ./downloads:/downloads
