version: "3.9"
services:
  radiko-auto-recorder:
    image: radiko-auto-recorder:latest
    container_name: radiko-auto-recorder
    volumes:
      - ./config.toml:/app/config.toml
      - ./downloads:/app/downloads
      - ./vendor:/build/vendor
